            <div class="headerContainer" id="headerContainer">
                <div class="headerMobile">
                    <div class="navHamburger">
                        <button class="menuClosed" id="button1">
                            <div class="navHIcons navIcon1"></div>
                            <div class="navHIcons navIcon2"></div>
                            <div class="navHIcons navIcon3"></div>
                            <div class="navHIcons navIcon4"></div>
                            <div class="navHIcons navIcon5"></div>
                        </button>
                    </div>
                    <div class="navExpandContainer" id="navExpand">
                        <nav class="navListContent">
                            <ul>
                                <li><a href="index">Home</a></li>
                                <li><a href="team">Team</a></li>
                                <li><a href="esports">Esports</a></li>
                                <li><a href="portraits">Portraits</a></li>
                                <li><a href="contact">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="logoContainer">
                        <a href="index">
                            <img src="images/logo.jpg" alt="Logo for PixelStrike Photography">
                        </a>
                    </div>
                </div>
                <div class="headerDesktop">
                    <div class="logoContainer">
                        <a href="index">
                            <img src="images/logo.jpg" alt="Logo for PixelStrike Photography">
                        </a>
                    </div>
                    <nav class="navContainer">
                        <ul>
                            <li><a href="index">Home</a></li>
                            <li><a href="team">Team</a></li>
                            <li><a href="esports">Esports</a></li>
                            <li><a href="portraits">Portraits</a></li>
                            <li><a href="contact">Contact</a></li>
                        </ul>
                    </nav>
                </div>
            </div>