            <header class="headerContainer" id="headerContainer">
                <div class="headerMobile">
                    <div class="navHamburger">
                        <button aria-label="Mobile Hamburger Menu that shows navigation options" class="menuClosed" id="button1">
                            <div class="navHIcons navIcon1"></div>
                            <div class="navHIcons navIcon2"></div>
                            <div class="navHIcons navIcon3"></div>
                            <div class="navHIcons navIcon4"></div>
                            <div class="navHIcons navIcon5"></div>
                        </button>
                    </div>
                    <div class="navExpandContainer" id="navExpand">
                        <nav class="navListContent">
                            <ul>
                                <li><a href="index">Home</a></li>
                                <li><a href="about">About</a></li>
                                <li><a href="coaches">Coaches</a></li>
                                <li><a href="class-outline">Class Outline</a></li>
                                <li><a href="contact">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="logoContainer">
                        <a href="index">
                            <img src="images/logo.png" alt="Logo for Enduro Edge Training">
                        </a>
                    </div>
                </div>
                <div class="headerDesktop">
                    <div class="headerContentContainer">
                        <div class="logoContainer">
                            <a href="index">
                                <img src="images/logo.png" alt="Logo for Enduro Edge Training">
                            </a>
                        </div>
                        <nav class="navContainer">
                            <ul>
                                <li><a href="index">Home</a></li>
                                <li><a href="about">About</a></li>
                                <li><a href="coaches">Coaches</a></li>
                                <li><a href="class-outline">Class Outline</a></li>
                                <li><a href="contact">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </header>